apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-client
  namespace: staging
  labels:
    app: blog-client
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-client
  template:
    metadata:
      labels:
        app: blog-client
        environment: staging
    spec:
      containers:
        - name: client
          image: DOCKERHUB_USERNAME/postpluse-client:latest
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "staging"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"