apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-backend
  namespace: staging
  labels:
    app: blog-backend
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-backend
  template:
    metadata:
      labels:
        app: blog-backend
        environment: staging
    spec:
      containers:
        - name: backend
          image: DOCKERHUB_USERNAME/postpluse-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "staging"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
